FROM registry.ci.openshift.org/ocp/4.21:base-rhel9

RUN dnf install -y iproute jq ipcalc && \
      dnf clean all && \
      rm -rf /var/cache/{yum,dnf}/*

COPY ./set-static-ip /set-static-ip
COPY ./refresh-static-ip /refresh-static-ip
