FROM registry.ci.openshift.org/ocp/builder:rhel-9-base-openshift-4.17

RUN dnf install -y iproute jq ipcalc && \
      dnf clean all && \
      rm -rf /var/cache/{yum,dnf}/*

COPY ./set-static-ip /set-static-ip
COPY ./refresh-static-ip /refresh-static-ip
